### ISSUE TITLE
Failed to install all requirements on macOS 

### ISSUE THREAD

**Issue by FeHoff** [EdoardoBettazzi/fMRI-signal-extraction#1]
I faile to install all python packages in both python venv and conda on macOS (old mac pro). On Debian Linux everything worked like charm. Maybe specify this in the README.

**Comment by EdoardoBettazzi** [comment]
Thanks for pointing out! I didn't test other environments than Linux Debian as the tool is developed for parallel computing on Linux machines, but I plan to! In the meantime I specified this in the README :)
